spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.generate_statistics: true

  datasource:
    hikari:
      max-lifetime: 1800000
      connection-timeout: 10000
      validation-timeout: 10000
      idle-timeout: 30000
      jdbc-url: jdbc:h2:~/jpa-custom-base-repository
      username: sa
      password:
      driver-class-name: org.h2.Driver
      maximum-pool-size: 10
      data-source-properties:
        profileSQL: true
        logger: Slf4JLogger

logging:
  level:
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.hibernate.SQL: DEBUG
    com.zaxxer.hikari: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework: INFO
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG

